-- Create account_type Data Type
create type public.account_type as enum('Client', 'Employee', 'Admin');
alter type public.account_type owner to cse340;
-- Create table classification
create table if not exists public.classification (
    classification_id integer generated by default as identity,
    classification_name character varying not null,
    constraint classification_pk primary key (classification_id)
);
-- Create table inventory
create table if not exists public.inventory (
    inv_id integer not null generated by default as identity,
    inv_make character varying not null,
    inv_model character varying not null,
    inv_year character(4) not null,
    inv_description text not null,
    inv_image character varying not null,
    inv_thumbnail character varying not null,
    inv_price numeric(9, 0) not null,
    inv_miles integer not null,
    inv_color character varying not null,
    classification_id integer not null,
    constraint invetory_pkey primary key(inv_id)
);
-- Add relationship between inventory and classification
alter table if exists public.inventory
add constraint fk_classification foreign key (classification_id) references classification (classification_id) match simple on
	update cascade on
		delete no action;
-- Create table account
create table if not exists public.account (
    account_id integer not null generated by default as identity,
    account_firstname character varying not null,
    account_lastname character varying not null,
    account_email character varying not null,
    account_password character varying not null,
    account_type account_type not null default 'Client'::account_type,
    constraint account_pkey primary key (account_id)
);